export const FLAG_OPTIONS: { flag: string; name: string }[] = [
  { flag: '🇦🇫', name: 'Afghanistan' },
  { flag: '🇦🇱', name: 'Albania' },
  { flag: '🇩🇿', name: 'Algeria' },
  { flag: '🇦🇷', name: 'Argentina' },
  { flag: '🇦🇲', name: 'Armenia' },
  { flag: '🇦🇺', name: 'Australia' },
  { flag: '🇦🇹', name: 'Austria' },
  { flag: '🇦🇿', name: 'Azerbaijan' },
  { flag: '🇧🇭', name: 'Bahrain' },
  { flag: '🇧🇩', name: 'Bangladesh' },
  { flag: '🇧🇾', name: 'Belarus' },
  { flag: '🇧🇪', name: 'Belgium' },
  { flag: '🇧🇴', name: 'Bolivia' },
  { flag: '🇧🇦', name: 'Bosnia' },
  { flag: '🇧🇷', name: 'Brazil' },
  { flag: '🇧🇬', name: 'Bulgaria' },
  { flag: '🇰🇭', name: 'Cambodia' },
  { flag: '🇨🇦', name: 'Canada' },
  { flag: '🇨🇱', name: 'Chile' },
  { flag: '🇨🇳', name: 'China' },
  { flag: '🇨🇴', name: 'Colombia' },
  { flag: '🇨🇷', name: 'Costa Rica' },
  { flag: '🇭🇷', name: 'Croatia' },
  { flag: '🇨🇺', name: 'Cuba' },
  { flag: '🇨🇾', name: 'Cyprus' },
  { flag: '🇨🇿', name: 'Czech Republic' },
  { flag: '🇩🇰', name: 'Denmark' },
  { flag: '🇩🇴', name: 'Dominican Republic' },
  { flag: '🇪🇨', name: 'Ecuador' },
  { flag: '🇪🇬', name: 'Egypt' },
  { flag: '🇸🇻', name: 'El Salvador' },
  { flag: '🇪🇪', name: 'Estonia' },
  { flag: '🇪🇹', name: 'Ethiopia' },
  { flag: '🇫🇮', name: 'Finland' },
  { flag: '🇫🇷', name: 'France' },
  { flag: '🇬🇪', name: 'Georgia' },
  { flag: '🇩🇪', name: 'Germany' },
  { flag: '🇬🇭', name: 'Ghana' },
  { flag: '🇬🇷', name: 'Greece' },
  { flag: '🇬🇹', name: 'Guatemala' },
  { flag: '🇭🇳', name: 'Honduras' },
  { flag: '🇭🇰', name: 'Hong Kong' },
  { flag: '🇭🇺', name: 'Hungary' },
  { flag: '🇮🇸', name: 'Iceland' },
  { flag: '🇮🇳', name: 'India' },
  { flag: '🇮🇩', name: 'Indonesia' },
  { flag: '🇮🇷', name: 'Iran' },
  { flag: '🇮🇶', name: 'Iraq' },
  { flag: '🇮🇪', name: 'Ireland' },
  { flag: '🇮🇱', name: 'Israel' },
  { flag: '🇮🇹', name: 'Italy' },
  { flag: '🇯🇲', name: 'Jamaica' },
  { flag: '🇯🇵', name: 'Japan' },
  { flag: '🇯🇴', name: 'Jordan' },
  { flag: '🇰🇿', name: 'Kazakhstan' },
  { flag: '🇰🇪', name: 'Kenya' },
  { flag: '🇰🇼', name: 'Kuwait' },
  { flag: '🇰🇬', name: 'Kyrgyzstan' },
  { flag: '🇱🇦', name: 'Laos' },
  { flag: '🇱🇻', name: 'Latvia' },
  { flag: '🇱🇧', name: 'Lebanon' },
  { flag: '🇱🇾', name: 'Libya' },
  { flag: '🇱🇹', name: 'Lithuania' },
  { flag: '🇱🇺', name: 'Luxembourg' },
  { flag: '🇲🇾', name: 'Malaysia' },
  { flag: '🇲🇻', name: 'Maldives' },
  { flag: '🇲🇱', name: 'Mali' },
  { flag: '🇲🇹', name: 'Malta' },
  { flag: '🇲🇽', name: 'Mexico' },
  { flag: '🇲🇩', name: 'Moldova' },
  { flag: '🇲🇳', name: 'Mongolia' },
  { flag: '🇲🇦', name: 'Morocco' },
  { flag: '🇲🇲', name: 'Myanmar' },
  { flag: '🇳🇵', name: 'Nepal' },
  { flag: '🇳🇱', name: 'Netherlands' },
  { flag: '🇳🇿', name: 'New Zealand' },
  { flag: '🇳🇮', name: 'Nicaragua' },
  { flag: '🇳🇬', name: 'Nigeria' },
  { flag: '🇲🇰', name: 'North Macedonia' },
  { flag: '🇳🇴', name: 'Norway' },
  { flag: '🇴🇲', name: 'Oman' },
  { flag: '🇵🇰', name: 'Pakistan' },
  { flag: '🇵🇦', name: 'Panama' },
  { flag: '🇵🇾', name: 'Paraguay' },
  { flag: '🇵🇪', name: 'Peru' },
  { flag: '🇵🇭', name: 'Philippines' },
  { flag: '🇵🇱', name: 'Poland' },
  { flag: '🇵🇹', name: 'Portugal' },
  { flag: '🇵🇷', name: 'Puerto Rico' },
  { flag: '🇶🇦', name: 'Qatar' },
  { flag: '🇷🇴', name: 'Romania' },
  { flag: '🇷🇺', name: 'Russia' },
  { flag: '🇷🇼', name: 'Rwanda' },
  { flag: '🇸🇦', name: 'Saudi Arabia' },
  { flag: '🇷🇸', name: 'Serbia' },
  { flag: '🇸🇬', name: 'Singapore' },
  { flag: '🇸🇰', name: 'Slovakia' },
  { flag: '🇸🇮', name: 'Slovenia' },
  { flag: '🇸🇴', name: 'Somalia' },
  { flag: '🇿🇦', name: 'South Africa' },
  { flag: '🇰🇷', name: 'South Korea' },
  { flag: '🇸🇸', name: 'South Sudan' },
  { flag: '🇪🇸', name: 'Spain' },
  { flag: '🇱🇰', name: 'Sri Lanka' },
  { flag: '🇸🇩', name: 'Sudan' },
  { flag: '🇸🇪', name: 'Sweden' },
  { flag: '🇨🇭', name: 'Switzerland' },
  { flag: '🇸🇾', name: 'Syria' },
  { flag: '🇹🇼', name: 'Taiwan' },
  { flag: '🇹🇯', name: 'Tajikistan' },
  { flag: '🇹🇿', name: 'Tanzania' },
  { flag: '🇹🇭', name: 'Thailand' },
  { flag: '🇹🇳', name: 'Tunisia' },
  { flag: '🇹🇷', name: 'Turkey' },
  { flag: '🇹🇲', name: 'Turkmenistan' },
  { flag: '🇺🇬', name: 'Uganda' },
  { flag: '🇺🇦', name: 'Ukraine' },
  { flag: '🇦🇪', name: 'UAE' },
  { flag: '🇬🇧', name: 'UK' },
  { flag: '🇺🇸', name: 'USA' },
  { flag: '🇺🇾', name: 'Uruguay' },
  { flag: '🇺🇿', name: 'Uzbekistan' },
  { flag: '🇻🇪', name: 'Venezuela' },
  { flag: '🇻🇳', name: 'Vietnam' },
  { flag: '🇾🇪', name: 'Yemen' },
  { flag: '🇿🇼', name: 'Zimbabwe' },
]
